In [13]:
def corner_to_center(corner_boxes):
    """
    input
    corner_boxes : corner coordinates boxes : [N, 4] (x1, y1, x2, y2)
    output
    center_boxes : center coordinates boxes : [N, 4] (cx, cy, w, h)
    """
    cxcy = (corner_boxes[..., :2] + corner_boxes[..., 2:4]) / 2
    print(corner_boxes[..., :2])
    print(corner_boxes[..., 2:4])
    print(cxcy)
    wh = corner_boxes[..., 2:4] - corner_boxes[..., :2]

    centor_boxes = torch.cat([cxcy, wh], dim=-1)
    return centor_boxes

In [14]:
def center_to_corner(center_boxes):
    """
    input
    center_boxes : center coordinates boxes : [N, 4] (cx, cy, w, h)
    output
    corner_boxes : corner coordinates boxes : [N, 4] (x1, y1, x2, y2)
    """
    x1y1 = center_boxes[..., :2] - (center_boxes[..., 2:4])/2
    x2y2 = center_boxes[..., :2] + (center_boxes[..., 2:4])/2
    corner_boxes = torch.cat([x1y1, x2y2], dim=-1)
    return corner_boxes

In [15]:
import torch

corner_boxes = torch.FloatTensor([10, 30, 140, 135])
center_boxes = corner_to_center(corner_boxes)

corner_boxes = center_to_corner(center_boxes)

tensor([10., 30.])
tensor([140., 135.])
tensor([75.0000, 82.5000])
